### ISSUE TITLE
[Bug] `debby/common.nim(141, 29) Error: undeclared field: 'id'`

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [treeform/debby#11]
Hi, I'm getting `/home/chronos/.nimble/pkgs2/debby-0.2.0-6508726171aee3c8fce349d1de788d41aae39bec/debby/common.nim(141, 29) Error: undeclared field: 'id'`

The code that triggered this was:
```nim
import debby/sqlite

let db = openDatabase(":memory:")

type
  DbObj = ref object of RootObj
    id*: int

  A = ref object of DbObj
    str: string

proc `$`(a: A): string = a.str

db.createTable(A)

db.insert(A(str: "wah!"))

var a = db.get(A, 1)

echo a
```

**Comment by treeform** [comment]
Sorry I don't support Nim's OOP.

Please use: ```nim
  A = ref object 
    id*: int
    str*: string
```

**Comment by enthus1ast** [comment]
@treeform 

i've the same issue:
```nim
import times
import debby/sqlite, jsony

type
  Base = ref object of RootObj
    id: int
  Foo = ref object of Base
    hihi: string

let db = openDatabase(":memory:")

try:
  db.createTable(Foo)
except:
  discard


let foo = Foo(hihi: "myfoo")
db.insert(foo)
echo db.get(Foo, 1)[]
```

But only this line in `debby/common.nim` prohibits this:
https://github.com/treeform/debby/blob/fa7bb049b0a5a5682792f23033583b58be3ce317/src/debby/common.nim#L142
if i remove this it works.

I use inheritance with debby in a project of mine, so far it seems to work. 
Only get has troubles.

My current workaround is to use `filter` instead of `get`.

```
let elems = pool.filter(MyType, it.id == id)
```

**Comment by treeform** [comment]
Sorry I don't support Nim's OOP please use plain Nim objects.
